# Docker Compose file for Odoo (version-agnostic via .env)

services:
  db:
    image: postgres:${POSTGRES_VERSION:-15}
    profiles: ["dev", "prod"]
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_HOST_PORT:-5433}:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    stop_grace_period: 60s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  odoo:
    build:
      context: .
      args:
        ODOO_VERSION: ${ODOO_VERSION:-18}
    profiles: ["dev", "prod"]
    depends_on:
      db:
        condition: service_healthy
    # Expose only longpolling internally; access Odoo through the proxy service on ${ODOO_HOST_PORT}
    ports:
      - "8072:8072"  # longpolling/websocket (bus) evented port
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8069/web/health >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 180s
    stop_grace_period: 60s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  proxy:
    image: nginx:alpine
    profiles: ["prod"]
    depends_on:
      odoo:
        condition: service_started
    ports:
      - "${ODOO_HOST_PORT:-8069}:8069"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8069/web/health >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  backup:
    image: postgres:${POSTGRES_VERSION:-15}
    profiles: ["prod"]
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGPASSWORD: odoo
    volumes:
      - odoo-backups:/backups
    entrypoint: ["bash", "-lc"]
    command: >-
      set -euo pipefail; 
      echo "Starting nightly backups to /backups"; 
      while true; do 
        ts=$(date +%Y%m%d-%H%M%S); 
        pg_dump -h db -U odoo -d odoo -F c -f /backups/odoo-$ts.dump; 
        find /backups -type f -name "*.dump" -mtime +7 -delete; 
        sleep 86400; 
      done
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  odoo-db-data:
  odoo-web-data:
  odoo-backups:
