# Docker Compose file for Odoo (version-agnostic via .env)

services:
  db:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    restart: unless-stopped

  odoo:
    build:
      context: .
      args:
        ODOO_VERSION: ${ODOO_VERSION}
    depends_on:
      - db
    ports:
      - "${ODOO_HOST_PORT}:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    restart: unless-stopped

volumes:
  odoo-db-data:
  odoo-web-data:
