apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: odoo
data:
  odoo.conf: |
    [options]
    ; admin_passwd and db_password are passed via container args from Kubernetes Secret
    db_host = postgres-service
    db_port = 5432
    db_user = odoo
    db_name = False
    db_template = template0
    db_sslmode = prefer
    addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
    data_dir = /var/lib/odoo
    log_level = info
    log_handler = :INFO
    ; Using stdout for logging
    max_cron_threads = 2
    workers = 2
    limit_memory_hard = 2684354560
    limit_memory_soft = 2147483648
    limit_request = 8192
    limit_time_cpu = 600
    limit_time_real = 1200
    limit_time_real_cron = 1200
    ; Enable proxy mode
    proxy_mode = True
    xmlrpc_port = 8069
    xmlrpc_interface = 0.0.0.0
