apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pvc
  namespace: odoo
spec:
  accessModes:
    - ReadWriteMany  # For multiple Odoo instances
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # Adjust based on your cluster's storage class

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: odoo
  labels:
    app: odoo
spec:
  replicas: 2  # Start with 2 instances
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: your-registry/odoo:latest  # Replace with your actual image
        ports:
        - containerPort: 8069
        env:
        - name: HOST
          value: postgres-service
        - name: USER
          value: odoo
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo-secrets
              key: postgres-password
        volumeMounts:
        - name: odoo-data
          mountPath: /var/lib/odoo
        - name: odoo-config
          mountPath: /etc/odoo
        - name: odoo-addons
          mountPath: /mnt/extra-addons
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /web/health
            port: 8069
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /web/health
            port: 8069
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: odoo-data
        persistentVolumeClaim:
          claimName: odoo-pvc
      - name: odoo-config
        configMap:
          name: odoo-config
      - name: odoo-addons
        emptyDir: {}  # You can mount your addons here or use a ConfigMap

---
apiVersion: v1
kind: Service
metadata:
  name: odoo-service
  namespace: odoo
  labels:
    app: odoo
spec:
  ports:
  - port: 8069
    targetPort: 8069
    protocol: TCP
  selector:
    app: odoo
  type: ClusterIP
