apiVersion: v1
kind: Secret
metadata:
  name: odoo-secrets
  namespace: odoo
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  # To encode: echo -n "your-password" | base64
  postgres-password: b2Rvbw==  # odoo
  odoo-admin-password: YWRtaW4=  # admin
  # Add more secrets as needed
  # aws-access-key: <base64-encoded-aws-access-key>
  # aws-secret-key: <base64-encoded-aws-secret-key>
