name: CD

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-image:
    name: Build and Push Docker Image to GHCR
    runs-on: ubuntu-latest
    env:
      ODOO_VERSION: "18"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute image name
        id: vars
        run: |
          REPO=${GITHUB_REPOSITORY#*/}
          OWNER=${GITHUB_REPOSITORY%/*}
          IMAGE="ghcr.io/${OWNER}/${REPO}"
          echo "IMAGE=${IMAGE,,}" >> $GITHUB_OUTPUT

      - name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.vars.outputs.IMAGE }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            ODOO_VERSION=${{ env.ODOO_VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Example deploy job (disabled). Uncomment and configure secrets to enable.
  # deploy:
  #   name: Deploy to Server via SSH
  #   needs: build-and-push-image
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   env:
  #     # Must match image computed above
  #     IMAGE: ghcr.io/${{ github.repository }}
  #   steps:
  #     - name: Deploy over SSH
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.DEPLOY_HOST }}
  #         username: ${{ secrets.DEPLOY_USER }}
  #         key: ${{ secrets.DEPLOY_SSH_KEY }}
  #         port: ${{ secrets.DEPLOY_PORT || 22 }}
  #         script: |
  #           docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
  #           docker pull ${IMAGE,,}:latest
  #           cd /srv/odooS
  #           docker compose down
  #           docker compose up -d
